name: projects

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=3.7.8"

dependencies:
  flutter:
    sdk: flutter
  
  image_network: 2.5.1

  core_ui:
    path: ../../core_ui

dev_dependencies:
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.5.1
