name: initial

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=3.7.8"

dependencies:
  flutter:
    sdk: flutter

  core_ui:
    path: ../../core_ui
  
  projects:
    path: ../projects

dev_dependencies:
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.5.1
