curl http://192.168.0.102:4444/albums

###

curl http://192.168.0.102:4444/albums/1

###

curl http://192.168.0.102:4444/albums \
    --include \
    --header "Content-Type: application/json" \
    --request "POST" \
    --data '{"id": "6","title": "The Modern Sound of Betty Carter","artist": "Betty Carter","price": 49.99}'

###

curl http://192.168.0.102:4444/albums \
    --include \
    --header "Content-Type: application/json" \
    --request "POST" \
    --data ''

###
curl http://192.168.0.102:4444/albums/2 \
    --request "DELETE"

###
curl http://192.168.0.102:4444/albums/1 \
    --request "PUT" \
    --data '{"title": "test"}'