name: core_ui

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=3.7.8"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: 8.1.2
  google_fonts: 4.0.3

dev_dependencies:
  flutter_lints: 2.0.1
  dart_code_metrics: 5.5.1

flutter:
  uses-material-design: true
